name: Snyk Security Scan

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (here we're using version 18 as an example)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies (npm install)
      - name: Install dependencies
        run: npm install

      # Run the Snyk security test to check for vulnerabilities
      - name: Run Snyk test
        uses: snyk/actions/node@master  # Use the latest version of snyk/actions
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Snyk API token from secrets
        with:
          command: test  # This checks for vulnerabilities

      # Optional: You can also monitor and send the snapshot to the Snyk dashboard
      # - name: Monitor with Snyk
      #   uses: snyk/actions/node@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     command: monitor  # This sends the snapshot to Snyk's dashboard
